package view;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;
import model.UserServices;
/**
 *
 * @author Cuong
 */
public class ResetPasswordUser extends javax.swing.JDialog {
    UserServices services;
    User u;
    static String password = null,rePassword = null;
    /**
     * Creates new form ResetPasswordUser
     */
    public ResetPasswordUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //WarningTextFiled.setVisible(false);
        initComponents();
    }
    public ResetPasswordUser(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        services = new UserServices();
        u = user;
        PasswordField.setDocument(new JTextFieldLimit(20));
        RePasswordField.setDocument(new JTextFieldLimit(20));
        RePasswordField.setEnabled(false);
        WarningTextFiled.setVisible(false);
        this.setIconImage(new ImageIcon("C:\\Users\\Cuong\\Documents\\NetBeansProjects\\FAMILY_FINANCE_APP\\src\\images\\resetPassword.png").getImage());
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RePasswordField = new javax.swing.JPasswordField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        WarningTextFiled = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reset Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 42, 355, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter your new password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 129, -1, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Retype new password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 180, 208, 32));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordField.setText("password");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 129, 273, -1));

        RePasswordField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RePasswordField.setText("password");
        RePasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RePasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RePasswordFieldFocusLost(evt);
            }
        });
        RePasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RePasswordFieldMouseClicked(evt);
            }
        });
        RePasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RePasswordFieldActionPerformed(evt);
            }
        });
        RePasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RePasswordFieldKeyTyped(evt);
            }
        });
        jPanel1.add(RePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 180, 273, -1));

        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaveButton.setText("Save password");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 272, 171, 45));

        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 272, 171, 45));

        WarningTextFiled.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        WarningTextFiled.setForeground(new java.awt.Color(204, 0, 0));
        WarningTextFiled.setText("(*) You have to enter new password first");
        jPanel1.add(WarningTextFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 233, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 722, 383));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        password = PasswordField.getText().trim();
        if(password.equals("password")) password = "";
        rePassword = RePasswordField.getText().trim();
        if(rePassword.equals("password")) rePassword = "";
        if(password.equals("")||rePassword.equals(""))
            JOptionPane.showMessageDialog(null, "You have to fill all blank");
        else if(!password.equals(rePassword))
            JOptionPane.showMessageDialog(null, "Your retype password is incorrect !");
        else if(password.length()<8){
            JOptionPane.showMessageDialog(null, "Your password mush have at least 8 character !");
            PasswordField.setText("");
            RePasswordField.setText("");
        }
        else{
            int certain = JOptionPane.showConfirmDialog(null, "Do you want to change password?");
            if(certain == 0){
                services.changePasswordUser(u, password);
                JOptionPane.showMessageDialog(null, "Change password successfully !\nRemember your password for the next login");
            }
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        String pass = String.valueOf(PasswordField.getPassword());
        WarningTextFiled.setVisible(false);
        if(PasswordField.getText().equals("password")){
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        String pass = String.valueOf(PasswordField.getPassword());
        if(pass.trim().equals("")||pass.trim().equals("password")){
            PasswordField.setText("password");
            PasswordField.setForeground(new Color(153,153,153));
        }
        PasswordField.setBorder(null);
    }//GEN-LAST:event_PasswordFieldFocusLost

    private void RePasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RePasswordFieldFocusGained
        String pass = String.valueOf(RePasswordField.getPassword());
        if(RePasswordField.getText().equals("password")){
            RePasswordField.setText("");
            RePasswordField.setForeground(Color.black);
        }
    }//GEN-LAST:event_RePasswordFieldFocusGained

    private void RePasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RePasswordFieldFocusLost
        String pass = String.valueOf(RePasswordField.getPassword());
        if(pass.trim().equals("")||pass.trim().equals("password")){
            RePasswordField.setText("password");
            RePasswordField.setForeground(new Color(153,153,153));
        }
        RePasswordField.setBorder(null);
    }//GEN-LAST:event_RePasswordFieldFocusLost

    private void RePasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RePasswordFieldKeyTyped
        
    }//GEN-LAST:event_RePasswordFieldKeyTyped

    private void RePasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RePasswordFieldMouseClicked
        password = PasswordField.getText().trim();
        if(password.equals("password")) password = "";
        RePasswordField.setText("");
        if(password.equals("")){
            RePasswordField.setEnabled(false);
            WarningTextFiled.setVisible(true);
        }
        else RePasswordField.setEnabled(true);
    }//GEN-LAST:event_RePasswordFieldMouseClicked

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void RePasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RePasswordFieldActionPerformed
        
    }//GEN-LAST:event_RePasswordFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField RePasswordField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel WarningTextFiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
